name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Deploy to VPS
        env:
          VPS_IP: ${{ secrets.VPS_IP }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_KEY: ${{ secrets.VPS_KEY }}
        run: |
          echo "$VPS_KEY" > key.pem
          chmod 600 key.pem
          scp -i key.pem -r . $VPS_USER@$VPS_IP:/var/www/efast-server
          ssh -i key.pem $VPS_USER@$VPS_IP "cd /var/www/efast-server && npm install && npm run startProd"
